### PR TITLE
Added line to say the installation needs Pillow as wx doesnt install …

### PR DESCRIPTION
**Pull request by iandobbie**
…it properly

### CODE REVIEW

**Comment by mickp** [comment]
@carandraug - can setup.py pull this in?

**Comment by iandobbie** [comment]
Yes but it is actually a wx dependency and David says they have fixed it just not yet in a release. This is why I put it in as 3a rather than fixing the whole readme properly.

Ian

Sent from my iPhone

On 15 Nov 2018, at 11:45, Mick <notifications@github.com<mailto:notifications@github.com>> wrote:


@carandraug<https://github.com/carandraug> - can setup.py pull this in?

**Comment by carandraug** [comment]
For reference, this is issue #319 . `setup.py` could easily pull this in. We don't do that because we're not dependent on Pillow and for all we know, wxPython could replace its use of Pillow with something else (and they actually have an open issue about using a lighter replacement).

The same logic why we didn't put it in `setup.py` can be applied to why we shouldn't put it on the `README`. But wxPython devs are taking some time to make a new release and I guess if we are pragmatic it's useful to list the dependency in which case, listing it on `setup.py` would be more useful than the `README`.

**Comment by iandobbie** [comment]
The reason I added it to the readme is we need the readme to actually reflect how to install cockpit.

It is quite difficult to do this well as our machines all already have the dependencies installed. I was installing cockpit on Ilan’s Mac Pro so had an opportunity to start from a fresh install.

Ian

Sent from my iPhone

On 15 Nov 2018, at 12:08, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


For reference, this is issue #319<https://github.com/MicronOxford/cockpit/issues/319> . setup.py could easily pull this in. We don't do that because we're not dependent on Pillow and for all we know, wxPython could replace its use of Pillow with something else (and they actually have an open issue about using a lighter replacement).

The same logic why we didn't put it in setup.py can be applied to why we shouldn't put it on the README. But wxPython devs are taking some time to make a new release and I guess if we are pragmatic it's useful to list the dependency in which case, listing it on setup.py would be more useful than the README.

**Comment by iandobbie** [comment]
Well if you add it to the setup.py could you remove the readme comment. I think in the sghort term it would be better in setup.py as this removes extra install steps.

**Pull request merged**
