### PR TITLE
Ximea camera

### PR DESCRIPTION
**Pull request by iandobbie**
Adds Ximea camera to universal camera and enables software triggers even when there is
a hardware trigger device.

### CODE REVIEW

**Comment by iandobbie** [comment]
Given the email I just sent this obviously isn't a single line change, seems there might be 3 lines changed (as well as useless white space). Obviously it now wont cleanly apply but should be a pretty easy fix. I will investigate.

**Comment by iandobbie** [comment]
Silly question but do we need this patch at all? I think the current microscopeCamera approach doesn't need any of this.

**Comment by mickp** [comment]
Yeah - I'd ditch it, and use the Microscope interface. The UniversalCamera class was the predecessor to Microscope, I think.

**Comment by iandobbie** [comment]
I dont think we need this any more, see comment by Mick above.

**Pull request closed without merging**
