### PR TITLE
Save absolute scaling values for reuse.

### LINKED ISSUE #423: mosaic autoscales images on import.
The mosaic now autoscales images on import. It shouldn't do this, it should use the current displayed values from the camera view window. Now every images has a different scale and is impossible to compare.

### PR DESCRIPTION
**Pull request by mickp**
Should fix #423.

### CODE REVIEW

**Comment by iandobbie** [comment]
I will test but This wont fix it as the histogram scale changes with every new image, it is just the display which doesn't.

**Comment by iandobbie** [comment]
As expected, change the exposure by 10x and the images are still equally bright. So it is once again autoscaling as the histogram autoscales on each exposure, however the actual scaling of the displayed image doesn't. See the numbers outside the brackets in the histogram display. As far as I can see these are just stored in tile[0][0], well as presumably all the other tiles as well.

**Comment by iandobbie** [comment]
Can we discus this versus #430 as I think this fix doesn't do what we need. We should try to cull the hanging pull requests anyway.

**Comment by iandobbie** [comment]
As no one has moved this on I think we should kill this pull request. CryoSIM is running #430 and appears to be working.

**Comment by carandraug** [comment]
Closing this, since it doesn't fix the issue.

**Pull request closed without merging**
