### PR TITLE
Fix ambient experiment

### LINKED ISSUE #795: Ambient Z-stack failing
It failed with the following error:
```

2022-01-24 15:20:12,948 INFO     experiment: 336  Experiment.execute started.
2022-01-24 15:20:13,496 ERROR    loggingWindow: 117  Exception in thread Experiment-execute:

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117  Traceback (most recent call last):

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117    File "C:\envs\cockpit\lib\threading.py", line 932, in _bootstrap_inner

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117      self.run()

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117    File "C:\envs\cockpit\lib\threading.py", line 870, in run

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117      self._target(*self._args, **self._kwargs)

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117    File "c:\b24\cockpit\cockpit\experiment\experiment.py", line 383, in execute

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117      raise RuntimeError("Found a line that no executor could handle: %s" % str(self.table.actions[curIndex]))

2022-01-24 15:20:13,496 ERROR    loggingWindow: 117  RuntimeError: Found a line that no executor could handle: (Decimal('0'), <light source named Ambient in group ambient>, True)
```

This is due to the name of the lights being compared to only `"ambient"` without capitalisation. I have a fix linked in #796 that offers a simple fix.

### PR DESCRIPTION
**Pull request by thomasmfish**
Also, I found a small weird check in structuredIllumination.py , which I've updated to what I think it probably _should_ be but it doesn't seem to cause an error.

Fixes #795

### CODE REVIEW

**Comment by iandobbie** [comment]
This fix wont work. If ambient is the last light then the longest wavelength will get set to -50 which is not what the code is meant to do. What is wrong with the original code?

**Comment by thomasmfish** [comment]
The change in experiment is necessary as it wasn't catching the capitalised case. The other change was a best guess at what the original code is supposed to do. It was checking if a wavelength value is `in ['Ambient', 'ambient']`, which makes no sense because it never would be.

**Comment by thomasmfish** [comment]
It seems like the entire check should probably be chucked out because I don't know what softworx has to do with the pupil edge

**Comment by thomasmfish** [comment]
I've committed some more changes to that file that removes the check for ambient entirely (since it was previously doing nothing) and offers a slight speed up

**Comment by thomasmfish** [comment]
If you'd like, revert the last two commits and just merge the fix that's definitely right

**Comment by thomasmfish** [comment]
@iandobbie I've separated out the bit you didn't like and the main fix now, so I think this should be fine to merge (have a look and see what you think). I'll open a separate issue to discuss the other bit.

**Comment by carandraug** [comment]
The fix was discussed on issue #738 . It has been fixed now (see discussion there). Closing.

**Pull request closed without merging**
