### PR TITLE
Decrease resource usage when idle

### PR DESCRIPTION
**Pull request by mickp**
On my system, cockpit was using most of a core's cycles even when idle. I've made a number of changes, and CPU usage will drop as low as 0% on idle, now.

* Added names to threads so we can see what is what in the debugger.
* Do GL primitive vertex calculations once, rather than on every update.
* Use vertex buffer objects for GL primitives, rather than a bunch of glBegin..draw..glEnd calls.
* Where possible, use the model-view matrix on the GPU to transform from stage to GL co-ordinates, rather than calculating every point in python.
* Touchscreen now runs the *same* drawing code as the canvases it clones, rather than a modified copy of that code.
* Fixed problems with touchscreen buttons.

### CODE REVIEW

**Comment by mickp** [comment]
I've just added some commits that make executors more flexible - this is required for @NickHallONBI's DM stuff.

**Comment by mickp** [comment]
Works on Manjaro on a VM. Some joystick issues.
* The VM has two virtual devices that are enumerated as joysticks, so I need to hard-code an ordinal to use the real joystick. Probably need a config entry to choose the right stick ... perhaps based on GetProductName?
* Button changes are enumerated differently compared to under Windows. This is a known wxWidgets issue, and I recently pushed fixes for this (wxWidgets/wxWidgets#971). It's unlikely that anyone is using cockpit on Linux with a joystick right now, so we should revisit this once the wxWidgets fix has made it into a release.

**Comment by iandobbie** [comment]
Sorry can't test of Mac currently as some weird wx bug is causing cockpit to segfault. I will investigate properly next week when I get back from holiday.

**Comment by mickp** [comment]
The Mac issue that Ian is seeing was introduced before this pull request, so I've opened issue #405 and will merge this now.

**Pull request merged**
