### PR TITLE
SIMFlux clean commits

### PR DESCRIPTION
**Pull request by NickHallONBI**
This branch just adds the 2D and 3D SIMFlux experiments to the experiments cockpit can perform.

2D SIMFlux is based on the 2D SIM experiment class and would require a hardware element to block the central beam.

3D SIMFlux is similarly based on the 3D SIM experiment class. It's worth noting that this is more of a theoretical forward thinking experiment. We're looking into ways to try and get some optical sectioning in 3D for SIMFlux and this is a first attempt at such a thing.

### CODE REVIEW

**Comment by carandraug** [comment]
This pull request copies a lot of code from the `cockpit.experiment.structuredIllumination` module to modify just a few things.  Removing the duplicated code on the experiment class seems pretty straightforward (see my [own branch with same name](https://github.com/carandraug/cockpit/tree/SIMFlux_clean_commits), or commit [de28bbf7795](https://github.com/carandraug/cockpit/commit/de28bbf779550cd2ad56926109b678bf9acbdd05)). However, avoiding the code duplication the actual experiment UI is a bit more tricky.

I have worked out something that could be used to avoid the duplication.  I have made that solution a separate branch from master and used to remove the duplication between the 2D and 3D SIM experiment UI (see my `sim-code-duplication-issue519` branch).

@NickHallONBI can you try it on DeepSIM? If it works there, then I will remove the rest of code duplication from this SIMFlux changes and merge it all.

**Comment by NickHallONBI** [comment]
Both your branch of SIMFlux_cleam_commits and sim-code-duplication-issue519 seem to run without issue on DeepSIM

**Comment by NickHallONBI** [comment]
David's [SIMFlux-squash-issue519](https://github.com/carandraug/cockpit/tree/SIMFlux-squash-issue519) works and removes a considerable amount of redundant code.

**Comment by carandraug** [comment]
The only difference between the 2D and 3D SIMFlux experiments is that the 3D has a checkbox to only use one angle. This was inherited from the SIM 3D but no longer makes sense because the SIMFlux UI has a text entry to enter the number of angles. I have spoke with @NickHallONBI about it and removed the checkbox from the SIMFlux UI.

Without the checkbox, and by inheriting from the base SIMUI, this pull request can be reduced to two new settings to the SIM experiment with 40 lines of code. I have done so on my `SIMFlux-squash-issue519` branch (or commit 0876179fe4eb). Nick has tested it on DeepSIM and reports it is working. It is now merged.

Closing as fixed.

**Pull request closed without merging**
