### PR TITLE
Implementing AO into cockpit

### PR DESCRIPTION
**Pull request by NickHallONBI**
Here is the current branch which is on DeepSIM and working. There are three main changes to MicronOxford/cockpit master:

1) An alpao device module

- This is a device module which doesn't exist in the master branch. It assumes that the back end is Microscope with the microscope-aotools extension. It creates a set of buttons in the UI, one labelled for calibration and one for general AO usage. 

2) Experiments which use the AO

- These are the remote focus calibration and remote focus Z-stack experiments.

3) Calculating centroids in the camera viewers

- This functionality eventually grew into BeamDelta, but Ian and I discussed that it was a useful functionality to have in Cockpit regardless so I have left it in there.

I am sure there are some issues that I have missed but I am creating this pull request so that we can review this code and edit such that it can be rolled into the default version of cockpit.

### CODE REVIEW

**Comment by carandraug** [comment]
Here's some comments after a quick glance:

* there are hardcoded paths for a user named nick in a directotry named cockpit
* this includes some GUI stuff that makes use of Tk
* this mixes the implementation of AO with showing centroids on the view canvas
* the class meant for deformable mirrors is very specific to Alpao. It is named alpao, the button also displays Alpao, and uses configuration values named alpao
* that class is far too long
* it includes annotations for an unresolved merge conflict

**Comment by NickHallONBI** [comment]
> there are hardcoded paths for a user named nick in a directotry named cockpit

Will fix in the next update

> this includes some GUI stuff that makes use of Tk

Presumably we should be using wx?

> this mixes the implementation of AO with showing centroids on the view canvas

Yep, will look for a way to extract those commits

> the class meant for deformable mirrors is very specific to Alpao. It is named alpao, the button also 
> displays Alpao, and uses configuration values named alpao
> that class is far too long

Will also change the instances of Alpao to a more generalised name. As for class length, I think some of that is unavoidable as it is also an executor device and the methods employed are necessary for complete control and calibration of any DM, not just an Alpao DM. We should talk about specific ways to trim this down at some point though.

> it includes annotations for an unresolved merge conflict

Where is this? I could seem to find it,

**Comment by carandraug** [comment]
>> this includes some GUI stuff that makes use of Tk
> Presumably we should be using wx?

Since this is for integration in cockpit, yes.

>> it includes annotations for an unresolved merge conflict
> Where is this? I could seem to find it,

Only on `README.md` just grep for `====` or `<<<<`

**Comment by NickHallONBI** [comment]
I have not done anything about the length of the class nor have I extracted all the stuff which is related to showing centroids in the ViewCanvas. However, all the hard-coded paths are gone and use os paths for each user and all the tk stuff has been nuked.

**Comment by NickHallONBI** [comment]
I believe that all the centroids viewer stuff is now gone so this pull request is purely implementing AO.

**Comment by mickp** [comment]
I've spent over 2 hours trying to unpick the conflicts in this mess, and got pretty much nowhere. It looks like the branch has been repeatedly rebased, modified, then merged with its unrebased version, so a number of commits have several copies which conflict with one another - in particular, a number of files are *created* in several different commits.

We can not merge this as it is.

**Pull request closed without merging**
