### PR TITLE
added Nicks centroid code to master

### PR DESCRIPTION
**Pull request by iandobbie**
Seems to still lacks display of delta distances, but other than that appears to work.

### CODE REVIEW

**Comment by iandobbie** [comment]
just realised this buggers up the new non-square image edits.... Will fix but maybe not tonight!

**Comment by NickHallONBI** [comment]
Apologies, I don't know how to add this to your branch. Just fetched your centroids branch and added this commit to it. Now the delta differences are displayed if a) they've been calculated and b) if the we are showing the current centroid. Please cherry pick this commit to add to your branch

Commit: 40f78a8c43f5d74e8fd5401c1133b0a4317ab7b8

**Comment by carandraug** [comment]
This pull request adds a new feature to the viewCanvas. When a new image is taken, it expects it to be a single spot and it will draw a cross on the centre of that spot. It also keeps a cross over an older centre. The use case of this is system alignment.

This is implemented by adding this new feature straight into the viewCanvas class which now becomes responsible for computing the centroids and whether it should be drawing them. I don't think this is a good idea. There are other things we will want to have displayed on top of the image. If the viewCanvas becomes responsible for this in this manner, it will become unmanageable, full of switch cases and conditions, and increasingly difficult to add the ability to draw new things, the most obvious of which is user draw regions for bleaching/activation.

An alternative could be for things to register with the viewCanvas. On receipt of a new image, the viewCanvas would call such things to have a go and draw things on the canvas. Depending on how this is done, this could enable the use of code external to cockpit to draw things on the viewCanvas.

**Comment by mickp** [comment]
Closing: superseded by #521.

**Pull request closed without merging**
