### PR TITLE
Deepsim

### PR DESCRIPTION
**Pull request by iandobbie**

### CODE REVIEW

**Comment by carandraug** [comment]
I'm the guessing the `dome.conf` file is being committed by accident. It should be removed.

**Comment by carandraug** [comment]
Also, this will not work in Python 3. At least the print statements need to be fixed. Did not look deeper than that.

**Comment by iandobbie** [comment]
Nope this is the branch for deepsim so should include the conf file.

Sent from my iPhone

On 30 Jul 2018, at 12:57, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm the guessing the dome.conf file is being committed by accident. It should be removed.

**Comment by carandraug** [comment]
> Nope this is the branch for deepsim so should include the conf file.

But you are requesting to have it pulled into master.

**Comment by iandobbie** [comment]
Mick created a new branch called deepsim by pulling directly from my repository so closing this.

**Pull request closed without merging**
