### PR TITLE
fixed stage mover so it moves on all axis even if current mover doesn…

### PR DESCRIPTION
**Pull request by iandobbie**
…t control this axis

This steps down through the movers to find the first that can perform the move on the selected axis. Means the keyboard motion works even if the current handler cant control that axis.

### CODE REVIEW

**Comment by carandraug** [comment]
Instead of adding an else with most of the internal logic repeated, this should be changed to act i two parts, 1: find the mover, 2 do the move.  Basically, move the call to `moveStep` out of the conditions. We should also not be modifying `curHandlerIndex` and if we really have to, then this needs to go into a `try/catch/finally`.

I propose something like this https://github.com/carandraug/cockpit/commit/d3b9e1913c78b20dbda0d8a2a220fa82abccb48d Other than the trying to fix this issue, it also removes the check of the axis even exists (because if it doesn't exist then we should error and not ignore?) and assumes that all axis have at least one handler (I was under the impression that this was a cockpit requirement).

**Comment by iandobbie** [comment]
I think a better approach might be to keep the step size from the previous mover if the current mover doesn’t support this axis. I did realise this was going to be an issue but thought it better to ignore it as my code did work just didn’t provide feedback on the step size.

Ian

Sent from my iPhone

On 8 Nov 2018, at 13:03, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


Instead of adding an else with most of the internal logic repeated, this should be changed to act i two parts, 1: find the mover, 2 do the move. Basically, move the call to moveStep out of the conditions. We should also not be modifying curHandlerIndex and if we really have to, then this needs to go into a try/catch/finally.

I propose something like this carandraug/cockpit@d3b9e19<https://github.com/carandraug/cockpit/commit/d3b9e1913c78b20dbda0d8a2a220fa82abccb48d> Other than the trying to fix this issue, it also removes the check of the axis even exists (because if it doesn't exist then we should error and not ignore?) and assumes that all axis have at least one handler (I was under the impression that this was a cockpit requirement).

**Comment by iandobbie** [comment]
Carnë Draug <notifications@github.com> writes:

> I went to try the fix on deepSIM and the change does mean that the
> stage now moves. However, I don't think there's a bug here, and that
> the proposed fix would introduce a bug. Here's why:

The bug is in the user-interface rather than the logic of the code. It
is very frustrating to have to keep switching mover to do XY, then focus
in Z then back to XY.....

I understand the logic behind not changing this, however from a
usability point of view we really need some solution to this.

Ian

**Comment by carandraug** [comment]
As discussed earlier today, we can hack this by making copies of the stages to that there's always an handler for each axis.  Here's a proposed change https://github.com/carandraug/cockpit/commit/18baf6bc6439bbc1e4ea10c2fd74a5cf896591ee that does it. It fixes point 2 of issue #413 about the step size.

**Comment by carandraug** [comment]
I have pushed 18baf6b which Nick tested has now tested  on deepSIM

**Pull request closed without merging**
